/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.saas.generic.business.feeds.schemas;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Index data Key schema to help you understand it's market value. */
@org.apache.avro.specific.AvroGenerated
public class IndexKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8035158985591844146L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexKey\",\"namespace\":\"com.saas.generic.business.feeds.schemas\",\"doc\":\"Index data Key schema to help you understand it's market value.\",\"fields\":[{\"name\":\"index\",\"type\":\"string\",\"doc\":\"Index\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IndexKey> ENCODER =
      new BinaryMessageEncoder<IndexKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IndexKey> DECODER =
      new BinaryMessageDecoder<IndexKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<IndexKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<IndexKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IndexKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this IndexKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a IndexKey from a ByteBuffer. */
  public static IndexKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Index */
  @Deprecated public CharSequence index;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IndexKey() {}

  /**
   * All-args constructor.
   * @param index Index
   */
  public IndexKey(CharSequence index) {
    this.index = index;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return index;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: index = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'index' field.
   * @return Index
   */
  public CharSequence getIndex() {
    return index;
  }

  /**
   * Sets the value of the 'index' field.
   * Index
   * @param value the value to set.
   */
  public void setIndex(CharSequence value) {
    this.index = value;
  }

  /**
   * Creates a new IndexKey RecordBuilder.
   * @return A new IndexKey RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new IndexKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IndexKey RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new IndexKey RecordBuilder by copying an existing IndexKey instance.
   * @param other The existing instance to copy.
   * @return A new IndexKey RecordBuilder
   */
  public static Builder newBuilder(IndexKey other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for IndexKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexKey>
    implements org.apache.avro.data.RecordBuilder<IndexKey> {

    /** Index */
    private CharSequence index;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing IndexKey instance
     * @param other The existing instance to copy.
     */
    private Builder(IndexKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'index' field.
      * Index
      * @return The value.
      */
    public CharSequence getIndex() {
      return index;
    }

    /**
      * Sets the value of the 'index' field.
      * Index
      * @param value The value of 'index'.
      * @return This builder.
      */
    public Builder setIndex(CharSequence value) {
      validate(fields()[0], value);
      this.index = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'index' field has been set.
      * Index
      * @return True if the 'index' field has been set, false otherwise.
      */
    public boolean hasIndex() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'index' field.
      * Index
      * @return This builder.
      */
    public Builder clearIndex() {
      index = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IndexKey build() {
      try {
        IndexKey record = new IndexKey();
        record.index = fieldSetFlags()[0] ? this.index : (CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IndexKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<IndexKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IndexKey>
    READER$ = (org.apache.avro.io.DatumReader<IndexKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
