server:
  port: 9071
spring:
  application:
    name: feedstreming
  batch:
    job.enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8082


feedstreming:
  applicationId: feed-stats-stream
  feedDataTopic: feed-data
  feedStatsTopic: feed-stats